project:
  type: website
  output-dir: docs
  
website:
  title: "Story Recipe: Severe Weather Damage in Texas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: 01-Cleaning.qmd
        text: Cleaning
      - href: 02-BasicAnalysis.qmd
        text: Statewide Analysis
      - href: 03-MoreAnalysis.qmd
        text: Interactive Table

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

df-print: paged


