project:
  type: website

website:
  title: "Story Recipe: Severe Weather Damage in Texas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - 01-Cleaning.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



